INSERT INTO destinations (destination, duration, details, price, image_path) VALUES
('Atene', '5 giorni', 'Scopri la storia antica e la cultura greca.', 450, 'atene.jpg'),
('Barcellona', '4 giorni', 'Arte, spiagge e tapas nella capitale catalana.', 520, 'barcellona.jpg'),
('Parigi', '6 giorni', 'Romanticismo, musei e cucina francese.', 700, 'parigi.jpg'),
('Londra', '5 giorni', 'Shopping, teatri e monumenti iconici.', 650, 'londra.jpg'),
('Roma', '3 giorni', 'Storia, arte e gastronomia italiana.', 400, 'roma.jpg'),
('Berlino', '4 giorni', 'Cultura alternativa e storia moderna.', 480, 'berlino.jpg'),
('Praga', '3 giorni', 'Atmosfera fiabesca e birra artigianale.', 350, 'praga.jpg'),
('Amsterdam', '4 giorni', 'Canali, musei e biciclette.', 550, 'amsterdam.jpg'),
('Vienna', '3 giorni', 'Musica classica e caffè storici.', 420, 'vienna.jpg'),
('Budapest', '4 giorni', 'Bagni termali e architettura.', 390, 'budapest.jpg'),
('Madrid', '5 giorni', 'Vita notturna e musei d’arte.', 530, 'madrid.jpg'),
('Lisboa', '4 giorni', 'Fado, tram storici e vista sull’oceano.', 470, 'lisboa.jpg'),
('Istanbul', '6 giorni', 'Tra Europa e Asia, bazar e moschee.', 600, 'istanbul.jpg'),
('Mosca', '5 giorni', 'Piazze storiche e cultura russa.', 750, 'mosca.jpg'),
('Dubai', '5 giorni', 'Grattacieli, shopping e deserto.', 900, 'dubai.jpg'),
('New York', '7 giorni', 'La città che non dorme mai.', 1200, 'new_york.jpg'),
('Tokyo', '6 giorni', 'Tecnologia, tradizione e sushi.', 1300, 'tokyo.jpg'),
('Bangkok', '5 giorni', 'Templi, mercati e street food.', 800, 'bangkok.jpg'),
('Sydney', '7 giorni', 'Spiagge, natura e cultura australiana.', 1500, 'sydney.jpg'),
('Rio de Janeiro', '6 giorni', 'Carnevale, spiagge e samba.', 1100, 'rio_de_janeiro.jpg');
